Initial implementation of addon store, api, and collection rendering …
OpenSourceTagpro/website pull request #5
Opened 2017-08-16 05:49 UTC by RonSpawnson

Getting my feet wet with by extending the project to add basic support for fetching and showing addons (addon store, api, and collection rendering). 

You can test it out by viewing the "recent" addons page. 

Caveat: The render is rough and needs styling/designing. I'm printing the values out right now as a stand-in placeholder.

2017-08-16 09:50 UTC, samhh requested changes
See notes. It's 95% there 👍

2017-08-16 09:50 UTC, SamHH commented on client/components/addons/addon-collection/addon-collection.js
> +		<div id={addon.name} key={addon.name}>
What's the `id` for?

2017-08-16 09:50 UTC, SamHH commented on client/components/addons/addon-collection/addon-collection.js
> +		<div id={addon.name} key={addon.name}>
Also semantically this should probably be a set of `<li>` wrapped in a `<ul>`.

2017-08-16 09:50 UTC, SamHH commented on client/components/addons/addon-collection/addon-collection.sass
> +		padding: 5px 0
Don't think you're using any of these styles at the moment?

2017-08-16 09:50 UTC, SamHH commented on client/components/addons/addon-collection/container.js
> +				addons={addon.addonsSortedByMostRecent}
You possibly shouldn't be specifying the addons here as now if you want to reuse this component on another page you're tied to having them sorted by most recent. Perhaps pass them in as a prop, and let the pages handle that contextually?

2017-08-16 09:50 UTC, SamHH commented on client/pages/addons/recent/recent.js
> +		addons: MobxPropTypes.observableArrayOf(MobxPropTypes.observableObject).isRequired
Don't think this is being used? But it probably should be, and passed into `<AddonCollection>` as a prop as I said above.

2017-08-16 09:50 UTC, SamHH commented on client/pages/addons/recent/recent.sass
> +		margin: 0 ($baseline-spacing / 3) ($baseline-spacing / 3) 0
Don't think you're using any of these styles at the moment?

2017-08-16 09:50 UTC, SamHH commented on client/stores/addon.js
> +export default new AddonStore()
Super duper minor nitpick: Would prefer if it was called `addons` store (plural). User store is singular as it was only supposed to hold the client alone (may also change, it's not scoped out).

2017-08-16 12:30 UTC, RonSpawnson commented on client/components/addons/addon-collection/addon-collection.js
> +		<div id={addon.name} key={addon.name}>
id is for nothing right now - I'll remove it as it has no use. Will also update to unordered list

2017-08-16 12:30 UTC, RonSpawnson commented on client/components/addons/addon-collection/addon-collection.sass
> +		padding: 5px 0
correct, I'll remove for clarity

2017-08-16 12:31 UTC, RonSpawnson commented on client/components/addons/addon-collection/container.js
> +				addons={addon.addonsSortedByMostRecent}
Yep, good catch. Will be needed to be able to reuse component for other orderings

2017-08-16 12:31 UTC, RonSpawnson commented on client/pages/addons/recent/recent.js
> +		addons: MobxPropTypes.observableArrayOf(MobxPropTypes.observableObject).isRequired
Yep, I agree

2017-08-16 12:33 UTC, RonSpawnson commented on client/stores/addon.js
> +export default new AddonStore()
Yeah I went back and forth on this. I've seen collections referred to with either naming convention, so I just picked one. Looking at it now I agree with your reasoning for the plural and will move to that

2017-08-16 12:34 UTC, RonSpawnson commented
I appreciate the feedback / nitipicks, especially as I get acquainted with the technology/project structure. 

I'll work on addressing the above and issuing a new diff once ready.

2017-09-03 18:50 UTC, RonSpawnson commented
Ready for re-review / merge.

Long term strategy may be to migrate to filterable/sortable table. Two pages - Store and Installed, or something like that

2017-09-04 15:09 UTC, samhh approved these changes

2017-09-04 15:09 UTC, merged